### ISSUE TITLE
addInterceptor not found 

### ISSUE THREAD

**Issue by crazyair** [NervJS/taro-plugin-platform-weapp-qy#3]
安装了这个插件 Taro 很多 api 没了？出于什么原因去掉呢？

**Comment by Chen-jj** [comment]
不会吧，提供一下 demo？

**Comment by anlia260** [comment]
我也是，麻烦提供一个 demo来。

**Comment by anlia260** [comment]
在taro项目中config/index.ts下，增加plugins。
在package.json 增加npm script

然后npm run dev:qywx ，项目中taro丢失了许多api。

**Comment by Chen-jj** [comment]
@crazyair @anlia260 没有复现

```js
import { View } from '@tarojs/components'
import { useEffect } from 'react'
import Taro from '@tarojs/taro'
import './index.scss'

export default function Index() {
  useEffect(() => {
    console.log('Taro: ', Taro)
  })

   return (
     <View>index</View>
   )
 }
```

![image](https://user-images.githubusercontent.com/11807297/120419185-88a4a600-c394-11eb-885c-6157575664fa.png)

可以逐步检查以下配置，如果还有问题请提供可复现 demo。

- 开发者工具的编译模式设置为：**企业微信小程序模式**
- Taro 的版本为 v3.1+
- 插件成功安装、配置

**Comment by panyu97py** [comment]
遇到了同样的问题
