### ISSUE TITLE
编译为企业微信小程序无法在微信开发者工具小程序模式中打开

### ISSUE THREAD

**Issue by flyfly6** [NervJS/taro-plugin-platform-weapp-qy#4]
编译为企业微信小程序后，在微信开发者工具中打开，企业微信小程序模式正常，但是在小程序模式中会报错。
由于通过插件引入了[通讯录展示组件](https://work.weixin.qq.com/api/doc/90001/90143/91958#3.1%20%E7%8E%AF%E5%A2%83%E8%A6%81%E6%B1%82)，而该插件无法在企业微信小程序模式下运行，开发者工具中只能在小程序模式中运行。
小程序模式中 wx.qy 是 undefined 导致代码这里报错了
https://github.com/NervJS/taro-plugin-platform-weapp-qy/blob/f97ea8f3bed82e76eff9fd455d211a472204eeb5/src/apis.ts#L10

**Comment by Chen-jj** [comment]
感觉这样没有问题吧。

Taro 编译企业微信小程序 -> 开发者工具使用企业微信小程序模式。
Taro 编译微信小程序 -> 开发者工具使用微信小程序模式。
