### ISSUE TITLE
Taro.qy is undefiend!

### ISSUE THREAD

**Issue by anlia260** [NervJS/taro-plugin-platform-weapp-qy#5]
can you give me a demo ???

**Comment by Chen-jj** [comment]
Duplicate of #3 

#3 中截图了，也回答了，就是文档中的这几步：https://docs.taro.zone/docs/next/GETTING-STARTED#%E4%BC%81%E4%B8%9A%E5%BE%AE%E4%BF%A1%E5%B0%8F%E7%A8%8B%E5%BA%8F
